sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 52YYttzz**

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  alioss:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7mR3VCMK57nDkf7kQV
    access-key-secret: gnXDEfJc8ldgtM2E8AEYUdiNgL9muQ
    bucket-name: sky-itcast-sunsiyi

  wechat:
    appid: wxda12afd18d6c8bbf
    secret: f63a43ca1f58411f61758265fb1afc17


